### ISSUE TITLE
Do not generate a inventory where a container will be on the rotating table

### ISSUE THREAD

**Issue by frederikhegger** [robocup-at-work/at_work_central_factory_hub#2]
From Jan: "In BTT2,3 and the Final we will Place objects in the Rotating Table. I was under the assumption, that the Table was rotating and did not think that it is too hard, to place an object on a rotating table. Since the ref-box may generate a command where it would be required to place an object in a container on top of a RT. I belief this to be too hard. Alex was under the assumption that the RT is off during the non CB tests. I would like to clarify this.

I would propose to let the table rotate and remove the option for the container to be on the rotating table."

**Comment by moriarty** [comment]
I believe I already pushed a fix to this and replied to Jan's email.

**Comment by JanCCarstensen** [comment]
Yes, i can confirm! Thanks Alex

**Comment by moriarty** [comment]
https://github.com/robocup-at-work/at_work_central_factory_hub/commit/e05ca184ba350cd7a3fa4d0d4f8cd3d10c277ed2
