### ISSUE TITLE
Use consistent naming for the CFH

### ISSUE THREAD

**Issue by frederikhegger** [robocup-at-work/at_work_central_factory_hub#3]
Since everything is tested for now, this should only be done after RoboCup 2016:

use a consistent naming, either refbox, cfh or something else (depending also on the integration with the logistics league):
- generated binaries (e.g. bin/refbox, bin/at-work-viewer, ...) and associate source and header files
- atwork_refbox_ros_client repository
- atwork_refbox_comm repository
- at_work_central_factory_hub repository
- ...

**Comment by moriarty** [comment]
I clarified that the Central Factory Hub and RefBox are interchangeable on the first line of the new "Overview" section of the Readme.

The messages for RoboCup@Work or ERL@Work will be ```atwork_``` prefixed in the future.

- https://github.com/robocup-industrial/rci_pb_msgs

I think the name for the CFH/Refbox is just RefBox.

- https://github.com/robocup-industrial/rci-refbox

The new messages are:

- rci_pb_msgs (time, beacon, and common messages between leagues)
- atwork_pb_msgs (@Work specific messages)
- atwork_device_pb_msgs (not seen on team side)
- rci_ros_msgs
- atwork_ros_msgs
